### ISSUE TITLE
Client does not reconnect after connection timed out

### ISSUE THREAD

**Issue by robindboer** [miguelgrinberg/python-engineio#110]
Hi I have a working socketio connection to a remote socketio server. Everything works just fine except at random intervals (mostly after a long period of inactivity) the connection drops out. When the connection drops out I expect it to recover and reconnect to the server automatically, however this does not happen. In the logs I see a recurring pattern when a dropout happens. See the logs below. What is causing this issue and how can I ensure the connection gets picked back up?

```2019-05-08 08:07:23,865 INFO  [socketio.client:402][Thread-21386] Received event "location" [/admin]
2019-05-08 08:07:47,814 INFO  [engineio.client:435][Thread-10977] Sending packet PING data None
2019-05-08 08:08:12,814 INFO  [engineio.client:492][Thread-10977] PONG response has not been received, aborting
2019-05-08 08:08:17,814 ERROR [engineio.client:591][Thread-10978] packet queue is empty, aborting
2019-05-08 08:08:17,817 INFO  [engineio.client:636][Thread-10978] Exiting write loop task
2019-05-08 08:23:32,639 INFO  [engineio.client:556][Thread-10979] Unexpected error "[Errno 110] Connection timed out", aborting
2019-05-08 08:23:32,639 INFO  [engineio.client:564][Thread-10979] Waiting for write loop task to end
2019-05-08 08:23:32,639 INFO  [engineio.client:566][Thread-10979] Waiting for ping loop task to end
2019-05-08 08:23:32,640 INFO  [engineio.client:500][Thread-10977] Exiting ping task
2019-05-08 08:23:32,640 INFO  [engineio.client:576][Thread-10979] Exiting read loop task```

**Comment by miguelgrinberg** [comment]
The reconnects are only triggered when there is a disconnection, not when there is an error.

In this case the client waited the necessary amount of time for a response from the server and didn't receive anything, while the server remained connected, so it appears that the server is not following the Socket.IO protocol.

What kind of server is this? Do you have control over it? Have you configured unusual timeouts for it?

**Comment by Q5Ca** [comment]
Hello @miguelgrinberg, this thread is quite long ago but I have question regarding it. 
My output log is similar to of @robindboer, which the reconnection start after `[Errno 110] Connection timed out` exception. In my case it took 15 minutes average after the timeout wait for PONG response.
After digging the source, I suppose it is because the exception is needed to break the recv loop in `_read_loop_websocket`.
So is it an expected beharvior? IMO, I would like the reconnection start right after `PONG response has not been received, aborting`. Can we make the socket recv timeout sooner or workaround something?

The environment I working on is: (I cant upgrade to python3 and the latest version of libraries because of problems with other dependencies)
```
python 2.7.17
python-socketio==4.4.0
python-engineio==3.11.0
```
And the device i'm working on is the jetson nano with ubuntu 18.04 for aarch64.

**Comment by miguelgrinberg** [comment]
@Q5Ca the question is why does your system take 15 minutes for the connection to end even though the server is not responding to pings. Do you know what is the server holding on to connections?

**Comment by Q5Ca** [comment]
The situation is I manually disconnected jetson(by unplug its internet cable) for testing purpose.
Server is running application based on `flask_socketio` and do basic stuff (i.e: adding jetson to room and emit message on specific user action)
Actually server can detect the disconnection about 1 minute after I disconnect jetson.

**Comment by miguelgrinberg** [comment]
Do you have any idea why it takes so long for your device to report a disconnection? I don't believe that is normal. Do you get the same effect when you do this disconnection test on a laptop or other computer?

**Comment by Q5Ca** [comment]
I retested on windows 7 and the reconnection started immediately. So sadly the problem is with the network stack on jetson ?

Besides, another issue is that after I re-enable the connection, the client keep throwing: `PONG response has not been received, aborting` and it attempt to reconnect infinitely.

**Comment by Q5Ca** [comment]
@miguelgrinberg I tested with python3 and `python-socketio==4.6.0` and `python-engineio==3.13.1` and it worked fine.
Is it possible to workaround by patching it to make it work with python2 ?
If yes, how can I diff two version ?

**Comment by miguelgrinberg** [comment]
I'm sorry, I don't understand what you are asking. Python 2 is currently unsupported and I have no plans to do any work on that release of Python. I'm slowing removing all the Pyhton 2'isms from the codebase to make the code cleaner and easier to maintain.

**Comment by Q5Ca** [comment]
well, actually my project sticks with python2 and as this issue #171 I cannot upgrade to latest version. So I just wonder if I can modify version 3.11.0 to make it work as expected.

**Comment by miguelgrinberg** [comment]
@Q5Ca have you identified what change in 3.12+ helps with your problem?

**Comment by Q5Ca** [comment]
I havent. Do you have any suggestion on finding that ?

**Comment by miguelgrinberg** [comment]
Maybe try every single version?

**Comment by Q5Ca** [comment]
There seems to be lots of work to do. I will try it.
Thanks for your kindly support.
