### ISSUE TITLE
asyncio support on Python 3.5

### ISSUE THREAD

**Issue by miguelgrinberg** [miguelgrinberg/python-engineio#23]

**Comment by miguelgrinberg** [comment]
Any brave souls that would like to test my first cut at supporting asyncio, please install master and take a look at the examples in the `examples/aiohttp` folder. These examples work with Python 3.5+ and require the aiohttp framework. Both long-polling and websocket transports are implemented.

**Comment by AlexElvers** [comment]
Thank you for your work! :)

After adding a long running operation to the message handler, I get a `concurrent.futures.CancelledError` when the client disconnects. When the program stops, there is still a pending task: the writer. This is because `await self.close(wait=True, abort=True)` and `await self.queue.put(None)` were not called after the exception (`asyncio_socket.py`).

Example handler:
```python
@eio.on('message')
async def message(sid, data):
    await eio.send(sid, 'pong', binary=False)
    await asyncio.sleep(1)
```

The solution might be another except case around `await self.receive(pkt)`
```python
except concurrent.futures.CancelledError:
    break
```

**Comment by miguelgrinberg** [comment]
I have been playing wack-a-mole with cancelled tasks yesterday. Looks like I still have a bit of work there to clean everything up. Thank you!

**Comment by miguelgrinberg** [comment]
@AlexElvers I think the problem you reported is resolved. Please reopen if you still get cancelled task errors.
