### ISSUE TITLE
other_asgi_app on_startup events no longer get executed

### ISSUE THREAD

**Issue by nossrannug** [miguelgrinberg/python-engineio#287]
**Describe the bug**
We're using FastAPI and all startup events no longer get executed after upgrading python-engineio to 4.3.3.
Version 4.3.2 works correctly.

**To Reproduce**
```python
# filename myapp.py

from fastapi import FastAPI
import socketio


def startup():
    print("here")

fastapi_app = FastAPI(
    on_startup=[startup],
)

sio = socketio.AsyncServer(cors_allowed_origins="*", async_mode="asgi")

app = socketio.ASGIApp(socketio_server=sio, socketio_path="/socket.io", other_asgi_app=fastapi_app)
```

Run with `uvicorn myapp:app`

**Expected behavior**
Running `uvicorn myapp:app` prints "here" to the console.

**Info**
Reverting this commit fixes it: https://github.com/miguelgrinberg/python-engineio/commit/c4a021ee9c4d760bbe4066887ca816fc7c718f98.
I didn't create a PR since I'm not sure what the correct order of the if statements should be.

**Comment by miguelgrinberg** [comment]
Oh, okay, I do see the problem.

With the 4.3.2 code the startup/shutdown events from the associated ASGI app were given preference over those in this library, and that was actually the bug that this contributor attempted to fix. Now startup/shutdown are not sent to the ASGI app anymore, because they are handled directly in the `ASGIApp` class, which also has `on_startup` and `on_shutdown` handlers.

Let me think about it. Maybe I can send these events to the ASGI app first, and if they aren't handled there send them to my own handlers. But I'm not sure if I can find out if an event was handled or not, need to look into that.

**Comment by miguelgrinberg** [comment]
Can I ask you to install and test the main branch? I think I have found a way to combine both lifespan handlers. The rules are as follow:

- If you have a companion ASGI app, and have not set the startup and shutdown events in the `ASGIApp` class, then lifespan events are forwarded to your ASGI app
- If there is no other ASGI app, or you have explicitly configured startup and/or shutdown events in `ASGIApp`, then lifespan events are not forwarded and handled internally.

**Comment by nossrannug** [comment]
This works :D
Thanks
