### ISSUE TITLE
url path is being stripped 

### ISSUE THREAD

**Issue by larsagny** [miguelgrinberg/python-engineio#297]
**Describe the bug**

I'm trying to connect to a socket.io endpoint served on `http://localhost:8080/socket/socket.io`. A request from the cmd line yields

```
curl "http://localhost:8080/socket/socket.io/?EIO=4&transport=polling"
0{"sid":"e6rTxVcthBhn9Ut1AAAC","upgrades":["websocket"],"pingTimeout":20000,"pingInterval":25000}⏎                                                                                            ~/D/g/l/live_assets ❯❯❯ [  ws]  (main)
```

When I try to establish the connection through python socket-io, however, I see this log statement that indicates that the `socket` part of the URL is being stripped.

   
**To Reproduce**

```
async def connect():
    print('connection established')


async def main():
    connector = aiohttp.TCPConnector(ssl=False)
    http_session = aiohttp.ClientSession(connector=connector)
    sio = socketio.AsyncClient(logger=True, engineio_logger=True, http_session=http_session)

    sio = socketio.AsyncClient(logger=True, engineio_logger=True, http_session=http_session)
    await sio.connect("ws://localhost:8080", namespaces=['/socket'])
    await sio.wait()


if __name__ == "__main__":
    asyncio.run(main())    
```

Output

```
Attempting polling connection to http://localhost:8080/socket.io/?transport=polling&EIO=4
```

I've tried to use the `namespaces` parameter like shown above, as well as 

```
    sio = socketio.AsyncClient(logger=True, engineio_logger=True, http_session=http_session)
    await sio.connect("ws://localhost:8080/socket")
    await sio.wait()
```
Both with same behavior. 

**Expected behavior**

The `_get_engineio_url` function calls `parsed_url = urllib.parse.urlparse(url)` which yields
```
In [1]: import urllib

In [2]:  parsed_url = urllib.parse.urlparse("ws://localhost:8080/socket")

In [3]: parsed_url
Out[3]: ParseResult(scheme='ws', netloc='localhost:8080', path='/socket', params='', query='', fragment='')
```

The `path` parameter is being dropped, I would expect the function to return: 
```
    def _get_engineio_url(self, url, engineio_path, transport):
        """Generate the Engine.IO connection URL."""
        engineio_path = engineio_path.strip('/')
        parsed_url = urllib.parse.urlparse(url)

        if transport == 'polling':
            scheme = 'http'
        elif transport == 'websocket':
            scheme = 'ws'
        else:  # pragma: no cover
            raise ValueError('invalid transport')
        if parsed_url.scheme in ['https', 'wss']:
            scheme += 's'

        return ('{scheme}://{netloc}{path}/?{query}'
                '{sep}transport={transport}&EIO=4').format(
                    scheme=scheme, netloc=parsed_url.netloc,
                    path=f"{parsed_url.path}/{engineio_path}", query=parsed_url.query,
                    sep='&' if parsed_url.query else '',
                    transport=transport)
```

**Comment by miguelgrinberg** [comment]
I don't think this is a bug, this library works exactly as its JavaScript counterpart.

If your Socket.IO endpoint is at `http://localhost:8080/socket/socket.io`, then you have to connect as follows:

```python
await sio.connect("ws://localhost:8080", path='/socket/socket.io')
```

You may or may not like how this works, but this has been the standard way to do it since the library started, and I imitated what the JS reference implementation does.

**Comment by larsagny** [comment]
I did look at the docs for a quite a while... :-/ 

You mean `socketio_path`? 
So I pass custom query string parameters on the **base** url like `http://localhost:8080?do_type=some`? 

Sorry to assume that this a bug but the docs did not give that away to easily.

**Comment by miguelgrinberg** [comment]
@larsagny sorry, yes, it is called `socketio_path`. I have corrected the example above.

The issue that you have is because you are trying to modify the Socket.IO endpoint. This is unusual, the protocol has a default endpoint and that is what most people use. Changing the endpoint is not done via the connection URL, the URL is always the domain and port. If you add a component to the connection URL, Socket.IO considers that the namespace, not the Socket.IO endpoint. This is very confusing, but that's the way things were designed by the authors of the Socket.IO protocol. The best thing you can do is work with the defaults, then everything just works.

**Comment by larsagny** [comment]
The endpoint I'm trying to connect to is not controlled by me and has the socket.io app mounted to a custom path. Anyways, thanks for the quick reply. I'm closing this thread now.
