### ISSUE TITLE
engineio incomaptible with aiohttp-3

### ISSUE THREAD

**Issue by maksbotan** [miguelgrinberg/python-engineio#62]
Hi! While debugging strange behaviour of Socket.IO with aiohttp server I've come across an issue in engineio.

You are calling `aiohttp.web.WebSocketResponse.send_str()` in `async_aiohttp.py`, but since aiohttp-3 this method is actually a coroutine, so you have to await it:

https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.WebSocketResponse.send_str

Can you please fix this? I can file a simple PR adding `await` and `aiohttp>3` requirement, but I guess you'd want to support both versions.

Right now I had to downgrade `aiohttp` on my server to workaround this.

**Comment by stephan48** [comment]
i am also affected by this bug. would it be possible to detect what type send_str is(function or coroutine) and await it conditionally?

**Comment by miguelgrinberg** [comment]
Yes, it is possible, that is actually how I'm going to fix it. Just did not get around to do it yet.

**Comment by stephan48** [comment]
Hi @miguelgrinberg,

Since my app requires aiohttp>=3,  I went ahead and proposed & tested a fix. Kind of wanted to test that little part of my work project before I go to bed.

Sadly i can't test it on aiohttp 2 atm due to time constraints. But i expect it to work - unless i forgot some Python certicularity. Please review and comment on my PR and maybe merge it, if it fits your liking :)

Thank you for you work!

--Stephan

**Comment by larry-dev** [comment]
@miguelgrinberg  When will the problem be repaired?  Thank you very much!

**Comment by miguelgrinberg** [comment]
Could any of you give the master branch a try? I think all the problems with aiohttp3 should be resolved now. If everything seems to be okay I'll cut a new release. Thanks!

**Comment by Kruptein** [comment]
I did a quick local update from the engineio master branch and the error is no longer being logged and websockets are being used instead of the polling mechanism.

**Comment by miguelgrinberg** [comment]
Fix released in v2.0.3.
