### ISSUE TITLE
random crash

### ISSUE THREAD

**Issue by plockaby** [miguelgrinberg/python-engineio#80]
I saw this in my logs today:

```
[2018-10-04 08:54:06,117] CRITICAL - WORKER TIMEOUT (pid:7669)
[2018-10-04 08:54:06,118] ERROR    - service task exception
Traceback (most recent call last):
  File "/netops/venv/events-portal-web/lib/python3.6/site-packages/engineio/server.py", line 524, in _service_task
    try:
  File "/netops/venv/events-portal-web/lib/python3.6/site-packages/gunicorn/workers/base.py", line 196, in handle_abort
    sys.exit(1)
SystemExit: 1
[2018-10-04 08:54:06,118] ERROR    - service task exception
Traceback (most recent call last):
  File "/netops/venv/events-portal-web/lib/python3.6/site-packages/engineio/server.py", line 524, in _service_task
    try:
  File "/netops/venv/events-portal-web/lib/python3.6/site-packages/gunicorn/workers/base.py", line 196, in handle_abort
    sys.exit(1)
SystemExit: 1
```

I'm not sure what else I have that I can provide but I'm hoping that this means something. It's the first time that I've seen this particular error after running this for a few months.

**Comment by miguelgrinberg** [comment]
It looks like your worker timed out and was being killed. The error is not indicative of any problems, just that this piece of code does not expect to be interrupted, and gunicorn killing the worker caused an interruption. The solution is to address the worker timeouts. Any idea what's causing them?

**Comment by miguelgrinberg** [comment]
The key log line is this one:

    [2018-10-04 08:54:06,117] CRITICAL - WORKER TIMEOUT (pid:7669)

This is unrelated to the crash, and also unrelated to the new service task feature, which runs in a background thread and does not block the worker. My guess is that if you run a version prior to 2.3.0 you will still see these timeouts.

Are you using eventlet or gevent for this application? If you do, the timeout error has a different meaning, it means that you are blocking for more than 30 seconds. If you are not using eventlet/gevent, then it means that a request took more than 30 seconds to complete. In either case, gunicorn is going to kill the worker and start a new one to replace it.

**Comment by Mostafa-Samir** [comment]
We have been encountering the exact same problem with my application. We're running with the following versions:
```
Flask-SocketIO==3.0.1
python-engineio==2.3.1  
python-socketio==2.0.0 
```
The same `service task exception` is raised when the `gunicorn` worker times out, and before it times out the application hangs with 100% CPU usage. My guess is that there's an infinite loop happening in the `_service_task` function and when `gunicorn` sends an interrupt to the non-responsive worker, the interrupt exception is raised within the loop. The problem is that this happens on a seemingly random situation, there's no distinct reproduction pattern, it can happen 20 mins after the app runs or after 10 hours of stably working.

We only encountered that error about 6 days ago when the deployment automatically updated to `python-engineio==2.3.1`. We have an older version of the app running on `python-socketio==2.0.0` where we don't encounter such behavior.

**Comment by miguelgrinberg** [comment]
I'll see what I can do to make this task exit cleanly, but you do realize this is a symptom of a larger problem, right? In previous versions, if your worker timed out, gunicorn would silently kill it and start another one. You now find out because of this background task. The worker timeout is the problem, the error in the service task is a side effect of that.

**Comment by miguelgrinberg** [comment]
@Mostafa-Samir @plockaby Can I ask you to test the master branch of python-engineio? I have put a fix that I think will allow for a graceful exit when the worker is killed. Let me know if this helps.

**Comment by plockaby** [comment]
Based on my access logs from gunicorn I'm not sure where a client request is timing out. There were no "normal" (non-websocket) requests to the application anywhere near where the exception happened. I suppose it's possible that the client's websocket connection somehow caused a timeout exception?

I'll install the master branch tomorrow, when I get back into the office. However, I've only seen this error three times in two weeks. (I'm assuming the KeyError exceptions that I got two weeks ago were related to this.) I'm not sure I'll be able to tell you definitively that it has ceased happening.

**Comment by miguelgrinberg** [comment]
@plockaby Have you ever seen this error before upgrading to the 2.3.x version of python-engineio? I'm trying to confirm that you had timeouts before the upgrade. I think this new service task could not be the cause of the timeout, but if you've never seen timeouts before maybe I should take another look.

**Comment by plockaby** [comment]
This particular error I've only seen since upgrade to 2.3.x. There was a different error before 2.3.x that we got a handful of times that said something like "KeyError Session not found". (Those logs have since rotated out but I really wish that I could show you.) Our application has been running since the beginning of July. This is our version history for this library:

2.3.1 deployed on October 3rd
2.3.0 deployed on September 27th
2.2.0 deployed on June 28th

So yes, I'd say that it started with 2.3.x.

**Comment by miguelgrinberg** [comment]
I believe v2.3.2 will address this problem. Please upgrade and keep an eye on the logs for a while. Let me know if it still happens.

**Comment by plockaby** [comment]
Thank you for looking into this. I'll let you know if I see any more errors. Otherwise this tool has been invaluable to us.
