### ISSUE TITLE
Considering implement shared session between multiple worker

### ISSUE THREAD

**Issue by StoneMoe** [miguelgrinberg/python-engineio#91]
I know this is an old question which already been mentioned many times since 2016 (maybe older), there are so many issues in python-engineio or flask-socketio about multiple worker thing.

So is there any chance that socket sessions can be shared between workers via uwsgi cache, nosql db or something else?

And I‘m planning override socketio.Server._engineio_server_class() as a workaround for now, am I doing it in the right way?

**Comment by miguelgrinberg** [comment]
> there are so many issues in python-engineio or flask-socketio about multiple worker thing

Really? What issues? Or do you mean that it is just tedious to set up? As far as I know multiple workers are fully functional, and they have been for a long time. I don't have any problems myself using multiple workers on my projects.

> is there any chance that socket sessions can be shared between workers

This is difficult to implement for the long polling transport, because at any given time a client has two outstanding requests. If these two end up on different workers, then the socket session needs to be carefully protected against concurrent access from the two workers handling the client at the same time. This is hard, and I also expect will affect performance in a considerable way.

If you restrict your clients to connect over the WebSocket transport only, then there is no need to share anything, because an entire Socket.IO session lives inside a single WebSocket request.

So if you want a simpler set up, then do not use long polling!

**Comment by StoneMoe** [comment]
Thanks for reply and your great project!

> Really? What issues? Or do you mean that it is just tedious to set up? 

The "issues" I mean is people's setup questions, sorry for my poor english :cry: 

The situation is, we want to support long polling for more compatibility, but can't replace the load balancer easily in our stack to support sticky session due to company's security policy, so maybe there is no simple way to support long polling for now...
